import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
  failOnWarn: false,
  externals: [
    // "consola",
    "dot-prop",
    "globby",
    "ohash",
    "pathe",
    "rollup",
    "ufo",
    "#nitro-internal-virtual/error-handler",
    "#nitro-internal-virtual/plugins",
    "#nitro-internal-virtual/server-handlers",
    "#nitro-internal-virtual/storage",
    "#nitro-internal-virtual/tasks",
    "#nitro-internal-virtual/database",
    "nitro/kit",
    "nitro/runtime",
    "consola",
    "consola/utils",
    "klona",
    "destr",
    "h3",
    "hookable",
    "ofetch",
    "unenv/runtime/fetch/index",
    "unstorage",
    "defu",
    "radix3",
    "unctx",
    "croner",
    "std-env",
    "db0",
    "scule",
    "cookie-es",
    "uncrypto",
    "iron-webcrypto",
    "unenv",
  ],
});
